sudo: false
language: python
python:
 - "3.4"
env:
  matrix:
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
install:
 - pip install $DJANGO 
 - pip install coverage
script: coverage run ematrikeln test 
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
