language: python
python:
    - "3.5"
env:
    -DJANGO=1.8.5
# command to install dependencies


install:
  -pip install django==1.8.5
  -pip install . 

# command to run tests
script:
    -python manage test

