language: python
python:
    - "3.5"
env:
    -DJANGO=1.8.5
# command to install dependencies

before_install:
  - export DJANGO_SETTINGS_MODULE=your_project.settings
  - export PYTHONPATH=$HOME/builds/your_github_username/your_repo
  - export PIP_USE_MIRRORS=true

install:
  - pip install django==$DJANGO --quiet

# command to run tests
script:
    -python manage test

