sudo: false
language: python
python:
 - "3.4"
 - "3.5"
env:
  matrix:
   - DJANGO="Django<1.8"
   - DJANGO="Django<1.9"
install:
 - pip install $DJANGO --use-mirrors
 - pip install coverage==3.7.1
script: coverage run manage.py test allauth
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
